version: '3.8'
services:
  server:
    container_name: crypto-bot-server
    build:
      context: ./app
      dockerfile: Dockerfile.local
    ports:
      - "5010:5000"
      - "5011:5001"
    depends_on:
      - db
    environment:
      API_KEY: ""
      API_SECRET: ""
      PYTHONPATH: /app/src
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      
  db:
    image: postgres:latest
    container_name: crypto-bot-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: crypto-bot-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# pg-admin settings
# host - db
# port - 5432
# password - postgres
# user - postgres

volumes:
  postgres_data:
  pgadmin_data: