version: '3.8'
services:
  # ui:
  #   container_name: crypto-bot-ui
  #   build:
  #     context: ./ui
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - "5012:3000"
  #     # - "5013:9229" # debug port
  #   depends_on:
  #     - server
  #   environment:
  #     REACT_APP_API_URL: http://localhost:5010
  #     WATCHPACK_POLLING: true
  #   volumes:
  #     - ./ui:/app
  #     - /app/node_modules

  server:
    container_name: crypto-bot-server
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - "5010:5000"
      - "5011:5001" # debug port
    depends_on:
      - db
    environment:
      API_KEY: ""
      API_SECRET: ""
      UI_URL: http://localhost:5012
      PYTHONPATH: /app/src
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      #NEED_TO_POST_SIGNALS_IN_TG: true
      CRYPTO_BOT_TOKEN: 6874810972:AAG6QTkvcU21ift9Ddpfe3IQNEgj5DxAqOw
      CRYPTO_BOT_INFO_CHAT_ID: -1002072371752
      CRYPTO_BOT_STATUS_CHAT_ID: -4068968943
      CRYPTO_BOT_SIGNALS_CHAT_ID: -4011804209
    volumes:
      - ./app:/app

volumes:
  postgres_data:

# docker-compose -f docker-compose-server-and-ui-prod.yml up --build -d