version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: crypto-bot-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

# docker-compose -f docker-compose-db-prod.yml up --build -d