#!/bin/bash

docker stop crypto-bot-server

delete_trade="DELETE FROM public.trade"
delete_asset="DELETE FROM public.asset"
delete_hold="DELETE FROM public.hold"

if [ "$strategy" != "" ]; then
        delete_trade+=" WHERE strategy = '${strategy}'"
        delete_asset+=" WHERE strategy = '${strategy}'"
        delete_hold+=" WHERE strategy = '${strategy}'"
fi

delete_trade+=";"
delete_asset+=";"
delete_hold+=";"

echo "$delete_trade" > /tmp/clear_data.sql
echo "$delete_asset" | tee -a /tmp/clear_data.sql
echo "$delete_hold" | tee -a /tmp/clear_data.sql

#cat /var/bot-app/crypto-bot/utils/db_scripts/clear_data.sql | docker exec -i crypto-bot-db psql -U postgres -d postgres
cat /tmp/clear_data.sql | docker exec -i crypto-bot-db psql -U postgres -d postgres

cd /var/bot-app/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d server

if [[ $? -ne 0 ]]; then
  exit 1
else
  exit 0
fi