#!/bin/bash

docker stop crypto-bot-server

cat /var/bot-app/crypto-bot/utils/db_scripts/clear_data.sql | docker exec -i crypto-bot-db psql -U postgres -d postgres

cd /var/bot-app/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d server

if [[ $? -ne 0 ]]; then
  exit 1
else
  exit 0
fi

