#!/bin/bash

#variables
deployment_logs_directory='/var/bot-app/logs/'
deployment_logs_file='/var/bot-app/logs/deployment.log'
dt=`date '+%d/%m/%Y %H:%M:%S'`

#check log directory
if [ ! -d deployment_logs_directory ]
then
  echo "creating $deployment_logs_directory"
  mkdir $deployment_logs_directory
fi

#check log files
if [ ! -f $deployment_logs_file ]
then
  echo "creating $deployment_logs_file"
  touch $deployment_logs_file
fi

#git pull repository
cd /var/bot-app/crypto-bot/
git config --global user.name "junkysoul"
git config --global user.email "dmitrystopkov@gmail.com"
eval $(ssh-agent -s)
ssh-add /root/github_ssh_keys/key
git pull git@github.com:Nikita628/crypto-bot.git prod

#run docker db
echo "running db docker"
printf "$dt running db docker\n" >> deployment_logs_file
cd /var/bot-app/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d db

#run migrations
echo 'migrations are running'
cd /var/bot-app/crypto-bot/utils/dbmate/ ; dbmate up
echo 'migrations running are ended'

#run docker server
echo "running server and ui docker"
printf "$dt running server and ui docker\n" >> deployment_logs_file
cd /var/bot-app/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d server

systemctl daemon-reload
systemctl restart bot_deployment_server