#!/bin/bash

#variables
deployment_log_file='/var/www/logs/deployment.log'
dt=`date '+%d/%m/%Y %H:%M:%S'`

#check log files
if [ ! -f $deployment_log_file ]
then
  echo "creating /var/www/logs/deployment.log"
  touch $deployment_log_file
fi

#check
if [ ! -d "/var/www/crypto-bot/" ]
then
  echo "/var/www/crypto-bot/ does not exist"
  printf "$dt /var/www/crypto-bot/ does not exist\n" >> $deployment_log_file
  mkdir /var/www/crypto-bot/
fi

#delete folder
if [ -d "/var/www/crypto-bot/bot/" ]
then
  echo "deleting /var/www/crypto-bot/bot"
  printf "$dt deleting /var/www/crypto-bot/bot\n" >> $deployment_log_file
  rm -r /var/www/crypto-bot/bot/
fi

#add folder
if [ ! -d "/var/www/crypto-bot/bot/" ]
then
  echo "adding /var/www/crypto-bot/bot/"
  printf "$dt adding /var/www/crypto-bot/bot/\n" >> $deployment_log_file
  mkdir /var/www/crypto-bot/bot/
fi

#git clone repository
cd /var/www/crypto-bot/bot/
git init
git config --global user.name "junkysoul"
git config --global user.email "dmitrystopkov@gmail.com"
eval $(ssh-agent -s)
ssh-add /root/github_ssh_keys/key
git pull -b prod git@github.com:Nikita628/crypto-bot.git

#move files
rm -r /var/www/crypto-bot/bot/.git/
mv /var/www/crypto-bot/bot/crypto-bot/* /var/www/crypto-bot/bot/

#move www folder content
mv /var/www/crypto-bot/bot/www/dbmate/db/migrations/* /var/www/dbmate/db/migrations/
mv /var/www/crypto-bot/bot/www/deployment_server/* /var/www/deployment_server/

#remove
rm -r /var/www/crypto-bot/bot/www/
rm -r /var/www/crypto-bot/bot/crypto-bot/

#run docker db
echo "running db docker"
printf "$dt running db docker\n" >> $deployment_log_file
cd /var/www/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d db

#run migrations
cd /var/www/dbmate/ ; dbmate up

#run docker server
echo "running server and ui docker"
printf "$dt running server and ui docker\n" >> $deployment_log_file
cd /var/www/crypto-bot/bot/
docker-compose -f docker-compose-prod.yml up --build -d server

systemctl restart bot_deployment_server