#!/bin/bash

#run docker db
echo "running db docker"
cd /var/bot-app/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d db

sleep 2

#run migrations
echo 'migrations are running'
cd /var/bot-app/crypto-bot/utils/dbmate/ ; dbmate up
echo 'migrations running are ended'

#run docker server
echo "running server and ui docker"
cd /var/bot-app/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d server
if [[ $? -ne 0 ]]; then
  exit 1
else
  exit 0
fi