#!/bin/bash

#git pull repository
cd /var/bot-app/crypto-bot/
git config --global user.name "junkysoul"
git config --global user.email "dmitrystopkov@gmail.com"
eval $(ssh-agent -s)
ssh-add /root/github_ssh_keys/key
git reset --hard
git pull git@github.com:Nikita628/crypto-bot.git prod

if [[ $? -ne 0 ]]; then
  exit 1
fi