#!/bin/bash

#git pull repository
cd /var/bot-app/crypto-bot/
git config --global user.name "junkysoul"
git config --global user.email "dmitrystopkov@gmail.com"
eval $(ssh-agent -s)
ssh-add /root/github_ssh_keys/key
git pull git@github.com:Nikita628/crypto-bot.git migrations_and_python_serveryyyy
systemctl daemon-reload
systemctl restart bot_deployment_server
if [[ $? -ne 0 ]]; then
  exit 1
fi