#!/bin/bash

#variables
deployment_logs_directory='/var/bot-app/logs/'
deployment_logs_file='/var/bot-app/logs/deployment.log'
dt=`date '+%d/%m/%Y %H:%M:%S'`

#delete
rm -r /var/bot-app/

#add folder
if [ ! -d "/var/bot-app/" ]
then
  echo "adding /var/bot-app/"
  printf "$dt adding /var/bot-app/\n" >> deployment_logs_file
  mkdir /var/bot-app/
fi

#check log directory
if [ ! -d $deployment_logs_directory ]
then
  echo "creating $deployment_logs_directory"
  mkdir $deployment_logs_directory
fi

#check log files
if [ ! -f $deployment_logs_file ]
then
  echo "creating $deployment_logs_file"
  touch $deployment_logs_file
fi

docker stop $(docker ps -a -q)
docker ps --filter status=exited -q | xargs docker rm
docker rmi $(docker images -q)

#git clone repository
cd /var/bot-app/
git init
git config --global user.name "junkysoul"
git config --global user.email "dmitrystopkov@gmail.com"
eval $(ssh-agent -s)
ssh-add /root/github_ssh_keys/key
git clone -b prod git@github.com:Nikita628/crypto-bot.git

#copy .env
cp /root/bot_env/dbmate/.env /var/bot-app/crypto-bot/utils/dbmate/
cp /root/bot_env/deployment_server/.env /var/bot-app/crypto-bot/utils/deployment_server/
cp /root/bot_env/docker/.env /var/bot-app/crypto-bot/

#run docker db
echo "running db docker"
printf "$dt running db docker\n" >> deployment_logs_file
cd /var/bot-app/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d db

#run docker server
echo "running server and ui docker"
printf "$dt running server and ui docker\n" >> deployment_logs_file
cd /var/bot-app/crypto-bot/
docker-compose -f docker-compose-prod.yml up --build -d server

#run migrations
echo 'migrations are running'
cd /var/bot-app/crypto-bot/utils/dbmate/ ; dbmate up
echo 'migrations running are ended'

systemctl daemon-reload
systemctl stop bot_deployment_server
systemctl start bot_deployment_server