FROM python:3.8

RUN pip install debugpy
RUN pip install watchdog

WORKDIR /app

COPY requirements.txt /app

RUN pip install -r requirements.txt

COPY . /app

RUN chmod +x entry_point.sh

CMD ["python", "-u", "change_watcher.py"]
