#!/bin/bash

#variables
deploying_log_file='/var/www/logs/deploying.log'
dt=`date '+%d/%m/%Y %H:%M:%S'`

echo 'restarting deployment server...'
printf "$dt restarting deployment server\n" >> $deploying_log_file
pkill -f deployment_server.py
if [ -f "/var/www/deployment_server/deployment_server.py" ]
then
  cd /var/www/deployment_server/
  screen -dmS python-http-server python3 deployment_server.py &
fi